[category.survivor]
en = "Survivor"
zh-Hans = "幸存者"

[category.skill]
en = "Skill"
zh-Hans = "技能"

[category.skin]
en = "Skin"
zh-Hans = "皮肤"

[category.item]
en = "Item"
zh-Hans = "物品"

[category.artifact]
en = "Artifact"
zh-Hans = "神器"

[category.stage]
en = "Stage"
zh-Hans = "关卡"

[category.secret_stage]
en = "Secret Stage"
zh-Hans = "隐藏关卡"

[category.monster_log]
en = "Monster Log"
zh-Hans = "怪物日志"

[category.trial]
en = "Providence Trial"
zh-Hans = "天命试炼"

[category.other]
en = "Other"
zh-Hans = "其他"

[status.locked]
en = "Locked"
zh-Hans = "未解锁"

[status.unlocked]
en = "Unlocked"
zh-Hans = "已解锁"

[survivor.commando]
en = "Commando"
zh-Hans = "指挥官"

[survivor.huntress]
en = "Huntress"
zh-Hans = "女猎人"

[survivor.enforcer]
en = "Enforcer"
zh-Hans = "执行者"

[survivor.bandit]
en = "Bandit"
zh-Hans = "潜行者"

[survivor.hand]
en = "HAN-D"
zh-Hans = "韩-迪"

[survivor.engineer]
en = "Engineer"
zh-Hans = "工程师"

[survivor.sniper]
en = "Sniper"
zh-Hans = "狙击手"

[survivor.acrid]
en = "Acrid"
zh-Hans = "呛鼻毒师"

[survivor.mercenary]
en = "Mercenary"
zh-Hans = "雇佣兵"

[survivor.loader]
en = "Loader"
zh-Hans = "装卸工"

[survivor.chef]
en = "CHEF"
zh-Hans = "大厨"

[survivor.pilot]
en = "Pilot"
zh-Hans = "领航员"

[survivor.arti]
en = "Artificer"
zh-Hans = "工匠"

[survivor.drifter]
en = "Drifter"
zh-Hans = "漂泊者"

[survivor.miner]
en = "Miner"
zh-Hans = "矿工"

[survivor.robomando]
en = "ROBOMANDO"
zh-Hans = "机械指挥官"

[stage.desolateForest]
en = "Desolate Forest"
zh-Hans = "荒凉森林"

[stage.driedLake]
en = "Dried Lake"
zh-Hans = "枯涸湖"

[stage.dampCaverns]
en = "Damp Caverns"
zh-Hans = "潮湿洞窟"

[stage.skyMeadow]
en = "Sky Meadow"
zh-Hans = "空中草原"

[stage.ancientValley]
en = "Ancient Valley"
zh-Hans = "远古峡谷"

[stage.sunkenTombs]
en = "Sunken Tombs"
zh-Hans = "沉没墓园"

[stage.magmaBarracks]
en = "Magma Barracks"
zh-Hans = "熔岩要塞"

[stage.hiveCluster]
en = "Hive Cluster"
zh-Hans = "虫巢"

[stage.templeOfTheElders]
en = "Temple of the Elders"
zh-Hans = "长老神殿"

[stage.riskOfRain]
en = "Risk of Rain"
zh-Hans = "暴雨滂沱"

[stage.boarBeach]
en = "Boar Beach"
zh-Hans = "野猪滩"

[stage.tutorial]
en = "Tutorial"
zh-Hans = "教程"

[stage.judgement]
en = "Judgement"
zh-Hans = "审判"

[stage.impShrine]
en = "Imp Shrine"
zh-Hans = "小恶魔神龛"

[stage.firstStagePool]
en = "Stage 1 Pool"
zh-Hans = "第一关卡池"

[stage.firstThreeStages]
en = "First Three Stages"
zh-Hans = "前三关"

[stage.thirdStagePool]
en = "Stage 3 Pool"
zh-Hans = "第三关卡池"
