schema_version = 1

[cognation]
icon = "icons/Artifact_of_Cognation_Select.png"

[cognation.name]
en = "Cognation"
zh-Hans = "相性"

[command]
icon = "icons/Artifact_of_Command_Select.png"

[command.name]
en = "Command"
zh-Hans = "统率"

[dissonance]
icon = "icons/Artifact_of_Dissonance_Select.png"

[dissonance.name]
en = "Dissonance"
zh-Hans = "纷争"

[distortion]
icon = "icons/Artifact_of_Distortion_Select.png"

[distortion.name]
en = "Distortion"
zh-Hans = "扭曲"

[enigma]
icon = "icons/Artifact_of_Enigma_Select.png"

[enigma.name]
en = "Enigma"
zh-Hans = "谜团"

[glass]
icon = "icons/Artifact_of_Glass_Select.png"

[glass.name]
en = "Glass"
zh-Hans = "玻璃"

[honor]
icon = "icons/Artifact_of_Honor_Select.png"

[honor.name]
en = "Honor"
zh-Hans = "荣耀"

[kin]
icon = "icons/ArtifactofKin_Select.png"

[kin.name]
en = "Kin"
zh-Hans = "亲族"

[mountain]
icon = "icons/Artifact_of_Prestige_Select.png"

[mountain.name]
en = "Prestige"
zh-Hans = "威望"

[origin]
icon = "icons/Artifact_of_Origin_Select.png"

[origin.name]
en = "Origin"
zh-Hans = "起源"

[sacrifice]
icon = "icons/Artifact_of_Sacrifice_Select.png"

[sacrifice.name]
en = "Sacrifice"
zh-Hans = "牺牲"

[spirit]
icon = "icons/Artifact_of_Spirit_Select.png"

[spirit.name]
en = "Spirit"
zh-Hans = "精神"

[spite]
icon = "icons/Artifact_of_Spite_Select.png"

[spite.name]
en = "Spite"
zh-Hans = "恶意"

[temporary]
icon = "icons/Artifact_of_Tempus_Select.png"

[temporary.name]
en = "Tempus"
zh-Hans = "须臾"
