schema_version = 1

[56LeafClover]
icon = "icons/56leafclover.png"

[56LeafClover.name]
en = "56 Leaf Clover"
zh-Hans = "五十六叶草"

[aegis]
icon = "icons/Aegis.png"

[aegis.name]
en = "Aegis"
zh-Hans = "庇护"

[alienHead]
icon = "icons/Alienhead.png"

[alienHead.name]
en = "Alien Head"
zh-Hans = "外星脑袋"

[ancientScepter]
icon = "icons/Ancientscepter.png"

[ancientScepter.name]
en = "Ancient Scepter"
zh-Hans = "远古权杖"

[arcaneBlades]
icon = "icons/Arcaneblades.png"

[arcaneBlades.name]
en = "Arcane Blades"
zh-Hans = "奥法秘刃"

[armsRace]
icon = "icons/Armsrace.png"

[armsRace.name]
en = "Arms Race"
zh-Hans = "军备竞赛"

[bitterRoot]
icon = "icons/Bitterroot.png"

[bitterRoot.name]
en = "Bitter Root"
zh-Hans = "苦根"

[bottledChaos]
icon = "icons/Bottledchaos.png"

[bottledChaos.name]
en = "Bottled Chaos"
zh-Hans = "瓶中混沌"

[captainsBrooch]
icon = "icons/Captainsbrooch.png"

[captainsBrooch.name]
en = "Captain's Brooch"
zh-Hans = "船长的胸针"

[chargefieldGenerator]
icon = "icons/Chargefieldgenerator.png"

[chargefieldGenerator.name]
en = "Chargefield Generator"
zh-Hans = "充能力场生成器"

[classifiedAccessCodes]
icon = "icons/Classifiedaccesscodes.png"

[classifiedAccessCodes.name]
en = "Classified Access Codes"
zh-Hans = "机密访问代码"

[concussionGrenade]
icon = "icons/Concussiongrenade.png"

[concussionGrenade.name]
en = "Concussion Grenade"
zh-Hans = "震荡手雷"

[crudelyDrawnBuddy]
icon = "icons/Crudelydrawnbuddy.png"

[crudelyDrawnBuddy.name]
en = "Crudely Drawn Buddy"
zh-Hans = "粗糙涂鸦伙伴"

[deadMansFoot]
icon = "icons/Deadmansfoot.png"

[deadMansFoot.name]
en = "Dead Man's Foot"
zh-Hans = "死人之脚"

[filialImprinting]
icon = "icons/Filialimprinting.png"

[filialImprinting.name]
en = "Filial Imprinting"
zh-Hans = "亲代印刻"

[firemansBoots]
icon = "icons/Firemansboots.png"

[firemansBoots.name]
en = "Fireman's Boots"
zh-Hans = "火人之靴"

[gasoline]
icon = "icons/Gasoline.png"

[gasoline.name]
en = "Gasoline"
zh-Hans = "汽油"

[giganticAmethyst]
icon = "icons/Giganticamethyst.png"

[giganticAmethyst.name]
en = "Gigantic Amethyst"
zh-Hans = "巨型紫水晶"

[glowingMeteorite]
icon = "icons/Glowingmeteorite.png"

[glowingMeteorite.name]
en = "Glowing Meteorite"
zh-Hans = "发光陨石"

[goldenGun]
icon = "icons/Goldengun.png"

[goldenGun.name]
en = "Golden Gun"
zh-Hans = "黄金枪"

[harvestersScythe]
icon = "icons/Harvestersscythe.png"

[harvestersScythe.name]
en = "Harvester's Scythe"
zh-Hans = "收割者镰刀"

[hermitsScarf]
icon = "icons/Hermitsscarf.png"

[hermitsScarf.name]
en = "Hermit's Scarf"
zh-Hans = "隐士的围巾"

[hopooFeather]
icon = "icons/Hopoofeather.png"

[hopooFeather.name]
en = "Hopoo Feather"
zh-Hans = "霍普羽毛"

[huntersHarpoon]
icon = "icons/Huntersharpoon.png"

[huntersHarpoon.name]
en = "Hunter's Harpoon"
zh-Hans = "猎人的鱼叉"

[hyperThreader]
icon = "icons/Hyperthreader.png"

[hyperThreader.name]
en = "Hyper-Threader"
zh-Hans = "超光速毒刺针"

[insecticide]
icon = "icons/Insecticide.png"

[insecticide.name]
en = "Insecticide"
zh-Hans = "杀虫剂"

[interstellarDeskPlant]
icon = "icons/Interstellardeskplant.png"

[interstellarDeskPlant.name]
en = "Interstellar Desk Plant"
zh-Hans = "星际桌子工厂"

[laserTurbine]
icon = "icons/Laserturbine.png"

[laserTurbine.name]
en = "Laser Turbine"
zh-Hans = "激光卡宾枪"

[lockedJewel]
icon = "icons/Lockedjewel.png"

[lockedJewel.name]
en = "Locked Jewel"
zh-Hans = "锁定的珠宝"

[lostDoll]
icon = "icons/Lostdoll.png"

[lostDoll.name]
en = "Lost Doll"
zh-Hans = "遗失的玩偶"

[maceReplica]
icon = "icons/Macereplica.png"

[maceReplica.name]
en = "Mace Replica"
zh-Hans = "权杖复制品"

[massiveLeech]
icon = "icons/Supermassiveleech.png"

[massiveLeech.name]
en = "Super Massive Leech"
zh-Hans = "超巨型水蛭"

[mocha]
icon = "icons/Mocha.png"

[mocha.name]
en = "Mocha"
zh-Hans = "抹茶"

[muConstruct]
icon = "icons/Muconstruct.png"

[muConstruct.name]
en = "Mu Construct"
zh-Hans = "Mu构造体"

[orbiter]
icon = "icons/Decayingsample.png"

[orbiter.name]
en = "Decaying Sample"
zh-Hans = "衰败样本"

[panicMines]
icon = "icons/Panicmines.png"

[panicMines.name]
en = "Panic Mines"
zh-Hans = "惊恐地雷"

[paulsGoatHoof]
icon = "icons/Paulsgoathoof.png"

[paulsGoatHoof.name]
en = "Paul's Goat Hoof"
zh-Hans = "保罗的山羊蹄"

[photonJetpack]
icon = "icons/Photonjetpack.png"

[photonJetpack.name]
en = "Photon Jetpack"
zh-Hans = "光子喷气背包"

[pillagedGold]
icon = "icons/Pillagedgold.png"

[pillagedGold.name]
en = "Pillaged Gold"
zh-Hans = "掠夺金钱"

[predatoryInstincts]
icon = "icons/Predatoryinstincts.png"

[predatoryInstincts.name]
en = "Predatory Instincts"
zh-Hans = "捕食本能"

[prescriptions]
icon = "icons/Prescriptions.png"

[prescriptions.name]
en = "Prescriptions"
zh-Hans = "处方药"

[prophetsCape]
icon = "icons/Prophetscape.png"

[prophetsCape.name]
en = "Prophet's Cape"
zh-Hans = "预言家的斗篷"

[razorPenny]
icon = "icons/Razorpenny.png"

[razorPenny.name]
en = "Razor Penny"
zh-Hans = "剃刀硬币"

[royalMedallion]
icon = "icons/Royalmedallion.png"

[royalMedallion.name]
en = "Royal Medallion"
zh-Hans = "皇家挂坠"

[rustyJetpack]
icon = "icons/Rustyjetpack.png"

[rustyJetpack.name]
en = "Rusty Jetpack"
zh-Hans = "生锈的喷气背包"

[shatteringJustice]
icon = "icons/Shatteringjustice.png"

[shatteringJustice.name]
en = "Shattering Justice"
zh-Hans = "粉碎之正义"

[shieldGenerator]
icon = "icons/Shieldgenerator.png"

[shieldGenerator.name]
en = "Shield Generator"
zh-Hans = "护盾生成器"

[snakeEyes]
icon = "icons/Snakeeyes.png"

[snakeEyes.name]
en = "Snake Eyes"
zh-Hans = "蛇眼"

[spikestrip]
icon = "icons/Spikestrip.png"

[spikestrip.name]
en = "Spikestrip"
zh-Hans = "钉刺带"

[stickyBomb]
icon = "icons/Stickybomb.png"

[stickyBomb.name]
en = "Sticky Bomb"
zh-Hans = "粘性炸弹"

[substandardDuplicator]
icon = "icons/Substandardduplicator.png"

[substandardDuplicator.name]
en = "Substandard Duplicator"
zh-Hans = "标准复制器"

[taser]
icon = "icons/Taser.png"

[taser.name]
en = "Taser"
zh-Hans = "电击枪"

[telescopicSight]
icon = "icons/Telescopicsight.png"

[telescopicSight.name]
en = "Telescopic Sight"
zh-Hans = "瞄准镜"

[theBackup]
icon = "icons/Thebackup.png"

[theBackup.name]
en = "The Back-up"
zh-Hans = "支援"

[theHitList]
icon = "icons/Thehitlist.png"

[theHitList.name]
en = "The Hit List"
zh-Hans = "诛杀令"

[theOlLopper]
icon = "icons/Ollopper.png"

[theOlLopper.name]
en = "The Ol' Lopper"
zh-Hans = "老砍子"

[theToxin]
icon = "icons/Thetoxin.png"

[theToxin.name]
en = "The Toxin"
zh-Hans = "毒素"

[toxicCentipede]
icon = "icons/Toxiccentipede.png"

[toxicCentipede.name]
en = "Toxic Centipede"
zh-Hans = "剧毒蜈蚣"

[umbrella]
icon = "icons/Umbrella.png"

[umbrella.name]
en = "Umbrella"
zh-Hans = "雨伞"

[unstableWatch]
icon = "icons/Unstable_Watch.png"

[unstableWatch.name]
en = "Unstable Watch"
zh-Hans = "不稳定手表"

[voltaicMitt]
icon = "icons/Voltaicmitt.png"

[voltaicMitt.name]
en = "Voltaic Mitt"
zh-Hans = "电伏手套"

[wickedRing]
icon = "icons/Wickedring.png"

[wickedRing.name]
en = "Wicked Ring"
zh-Hans = "邪恶的戒指"
