schema_version = 1

[ancientWisp]
icon = "icons/Ancient_Wisp_Icon.gif"

[ancientWisp.name]
en = "Ancient Wisp"
zh-Hans = "远古幽魂"

[archerBug]
icon = "icons/Archer_Bug_Icon.gif"

[archerBug.name]
en = "Archer Bug"
zh-Hans = "射手虫"

[bighornBison]
icon = "icons/Bighorn_Bison_Icon.gif"

[bighornBison.name]
en = "Bighorn Bison"
zh-Hans = "巨角野牛"

[blackImp]
icon = "icons/Black_Imp_Icon.gif"

[blackImp.name]
en = "Black Imp"
zh-Hans = "黑小恶魔"

[bramble]
icon = "icons/Bramble_Icon.gif"

[bramble.name]
en = "Bramble"
zh-Hans = "荆棘"

[child]
icon = "icons/Child_Icon.gif"

[child.name]
en = "Child"
zh-Hans = "魔童"

[clayMan]
icon = "icons/Clay_Man_Icon.gif"

[clayMan.name]
en = "Clay Man"
zh-Hans = "粘土人"

[colossus]
icon = "icons/Colossus_Icon.gif"

[colossus.name]
en = "Colossus"
zh-Hans = "巨像"

[cremator]
icon = "icons/Cremator_Icon.gif"

[cremator.name]
en = "Cremator"
zh-Hans = "火焚怪"

[elderLemurian]
icon = "icons/Elder_Lemurian_Icon.gif"

[elderLemurian.name]
en = "Elder Lemurian"
zh-Hans = "利莫里亚长老"

[evolvedLemurian]
icon = "icons/Evolved_Lemurian_Icon.gif"

[evolvedLemurian.name]
en = "Evolved Lemurian"
zh-Hans = "飞天利莫里亚人"

[greaterWisp]
icon = "icons/Greater_Wisp_Icon.gif"

[greaterWisp.name]
en = "Greater Wisp"
zh-Hans = "巨型幽魂"

[gup]
icon = "icons/Gup_Icon.gif"

[gup.name]
en = "Gup"
zh-Hans = "加普"

[ifrit]
icon = "icons/Ifrit_Icon.gif"

[ifrit.name]
en = "Ifrit"
zh-Hans = "伊夫利特"

[impOverlord]
icon = "icons/Imp_Overlord_Icon.gif"

[impOverlord.name]
en = "Imp Overlord"
zh-Hans = "小恶魔霸主"

[jellyfish]
icon = "icons/Jellyfish_Icon.gif"

[jellyfish.name]
en = "Jellyfish"
zh-Hans = "水母"

[lemurian]
icon = "icons/Lemurian_Icon.gif"

[lemurian.name]
en = "Lemurian"
zh-Hans = "利莫里亚人"

[lemurianCavalry]
icon = "icons/Lemurian_Cavalry_Icon.gif"

[lemurianCavalry.name]
en = "Lemurian Cavalry"
zh-Hans = "利莫里亚骑兵"

[lynxTotem]
icon = "icons/Lynx_Totem_Icon.gif"

[lynxTotem.name]
en = "Lynx Totem"
zh-Hans = "猞猁图腾"

[lynxTribe]
icon = "icons/Lynx_Tribe_Icon.gif"

[lynxTribe.name]
en = "Lynx Tribe"
zh-Hans = "猞猁部落"

[macrobe]
icon = "icons/Macrobe_Icon.gif"

[macrobe.name]
en = "Macrobe"
zh-Hans = "巨生物"

[macrobicPredator]
icon = "icons/Macrobic_Predator_Icon.gif"

[macrobicPredator.name]
en = "Macrobic Predator"
zh-Hans = "巨生物捕食者"

[magmaWorm]
icon = "icons/Magma_Worm_Icon.gif"

[magmaWorm.name]
en = "Magma Worm"
zh-Hans = "岩浆蠕虫"

[mechanicalSpider]
icon = "icons/Mechanical_Spider_Icon.gif"

[mechanicalSpider.name]
en = "Mechanical Spider"
zh-Hans = "机械蜘蛛"

[mushrum]
icon = "icons/Mushrum_Icon.gif"

[mushrum.name]
en = "Mushrum"
zh-Hans = "走路菇"

[parent]
icon = "icons/Parent_Icon.gif"

[parent.name]
en = "Parent"
zh-Hans = "祖人"

[providence]
icon = "icons/Providence_Icon.gif"

[providence.name]
en = "Providence"
zh-Hans = "天命"

[rockGolem]
icon = "icons/Rock_Golem_Icon.gif"

[rockGolem.name]
en = "Rock Golem"
zh-Hans = "石傀儡"

[sandCrab]
icon = "icons/Sand_Crab_Icon.gif"

[sandCrab.name]
en = "Sand Crab"
zh-Hans = "沙蟹"

[scavenger]
icon = "icons/Scavenger_Icon.gif"

[scavenger.name]
en = "Scavenger"
zh-Hans = "清道夫"

[spitter]
icon = "icons/Spitter_Icon.gif"

[spitter.name]
en = "Spitter"
zh-Hans = "喷吐兽"

[swift]
icon = "icons/Swift_Icon.gif"

[swift.name]
en = "Swift"
zh-Hans = "迅捷"

[templeGuard]
icon = "icons/Temple_Guard_Icon.gif"

[templeGuard.name]
en = "Temple Guard"
zh-Hans = "神殿守卫"

[tinyImp]
icon = "icons/Tiny_Imp_Icon.gif"

[tinyImp.name]
en = "Tiny Imp"
zh-Hans = "小不点小恶魔"

[toxicBeast]
icon = "icons/Toxic_Beast_Icon.gif"

[toxicBeast.name]
en = "Toxic Beast"
zh-Hans = "猛毒巨兽"

[trokk]
icon = "icons/Trokk_Icon.gif"

[trokk.name]
en = "Trokk"
zh-Hans = "托克"

[tuber]
icon = "icons/Tuber_Icon.gif"

[tuber.name]
en = "Tuber"
zh-Hans = "块茎"

[wanderingVagrant]
icon = "icons/Wandering_Vagrant_Icon.gif"

[wanderingVagrant.name]
en = "Wandering Vagrant"
zh-Hans = "漫游者"

[whorl]
icon = "icons/Whorl_Icon.gif"

[whorl.name]
en = "Whorl"
zh-Hans = "漩涡螺"

[wisp]
icon = "icons/Wisp_Icon.gif"

[wisp.name]
en = "Wisp"
zh-Hans = "幽魂"
