schema_version = 1

[equipmentActivator]
url = "https://riskofrainreturns.wiki.gg/wiki/Equipment_Activator"

  [equipmentActivator.name]
  en = "Equipment Activator"
  zh-Hans = "装备激活器"

[trials]
icon = "icons/ProvidenceTrials.png"

  [trials.name]
  en = "Divine Intervention"
  zh-Hans = "天意难违"
