schema_version = 1

[acrid.acrid_skin_s]
icon = "icons/AcridPortrait0.png"
owner = "survivor.acrid"

  [acrid.acrid_skin_s.name]
  en = "Strange Prism: Calcium"
  zh-Hans = "奇怪棱镜：钙"

  [acrid.acrid_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:acrid"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_acrid_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[acrid.acrid_skin_s2]
icon = "icons/AcridPortrait0.png"
owner = "survivor.acrid"

  [acrid.acrid_skin_s2.name]
  en = "Strange Prism: Obsidian"
  zh-Hans = "奇怪棱镜：黑曜石"

  [acrid.acrid_skin_s2.game]
  content_class = "skin_slot"
  owner_game_id = "ror:acrid"
  skin_slot = 5
  skin_id = 5
  achievement_id = "unlock_acrid_skin_s2"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[arti.arti_skin_s]
icon = "icons/ArtificerPortrait0.png"
owner = "survivor.arti"

  [arti.arti_skin_s.name]
  en = "Strange Prism: Stasis"
  zh-Hans = "奇怪棱镜：静滞"

  [arti.arti_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:arti"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_arti_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[bandit.bandit_skin_s]
icon = "icons/BanditPortrait0.png"
owner = "survivor.bandit"

  [bandit.bandit_skin_s.name]
  en = "Strange Prism: Snare"
  zh-Hans = "奇怪棱镜：阻滞"

  [bandit.bandit_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:bandit"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_bandit_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[chef.chef_skin_s]
icon = "icons/CHEFPortrait0.png"
owner = "survivor.chef"

  [chef.chef_skin_s.name]
  en = "Unethical Consumption"
  zh-Hans = "肆无忌惮"

  [chef.chef_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:chef"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_chef_skin_s"
  progress_needed = 1
  death_reset = false
  achievement_group = "challenge"
  achievement_hidden = true

[commando.commando_skin_s]
icon = "icons/CommandoPortrait0.png"
owner = "survivor.commando"

  [commando.commando_skin_s.name]
  en = "Strange Prism: Pyrite"
  zh-Hans = "奇怪棱镜：硫化铁"

  [commando.commando_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:commando"
  skin_slot = 5
  skin_id = 5
  achievement_id = "unlock_commando_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[drifter.drifter_skin_s]
icon = "icons/DrifterPortrait0.png"
owner = "survivor.drifter"

  [drifter.drifter_skin_s.name]
  en = "Strange Prism: Pollen"
  zh-Hans = "奇怪棱镜：花粉"

  [drifter.drifter_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:drifter"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_drifter_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[huntress.huntress_skin_s]
icon = "icons/HuntressPortrait0.png"
owner = "survivor.huntress"

  [huntress.huntress_skin_s.name]
  en = "Strange Prism: Extinction"
  zh-Hans = "奇怪棱镜：灭绝"

  [huntress.huntress_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:huntress"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_huntress_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[loader.loader_skin_s]
icon = "icons/LoaderPortrait0.png"
owner = "survivor.loader"

  [loader.loader_skin_s.name]
  en = "Strange Prism: Nebula"
  zh-Hans = "奇怪棱镜：星云"

  [loader.loader_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:loader"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_loader_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[mercenary.mercenary_skin_s]
icon = "icons/MercenaryPortrait0.png"
owner = "survivor.mercenary"

  [mercenary.mercenary_skin_s.name]
  en = "Strange Prism: Malice"
  zh-Hans = "奇怪棱镜：恶意"

  [mercenary.mercenary_skin_s.game]
  content_class = "skin_slot"
  owner_game_id = "ror:mercenary"
  skin_slot = 4
  skin_id = 4
  achievement_id = "unlock_mercenary_skin_s"
  progress_needed = 1
  death_reset = true
  achievement_group = "character"
  achievement_hidden = true

[pilot.pilot_skin_s]
icon = "icons/PilotPortrait0.png"
owner = "survivor.pilot"

  [pilot.pilot_skin_s.name]
  en = "Strange Prism: Napalm"
  zh-Hans = "奇怪棱镜：凝固汽油"
