schema_version = 1

[ancientValley]
icon = "icons/AncientValleySC.png"

[ancientValley.name]
en = "Ancient Valley"
zh-Hans = "远古峡谷"

[boarBeach]
icon = "icons/BoarBeachSC.png"

[boarBeach.name]
en = "Boar Beach"
zh-Hans = "野猪滩"

[dampCaverns]
icon = "icons/DampCavernsSC.jpg"

[dampCaverns.name]
en = "Damp Caverns"
zh-Hans = "潮湿洞窟"

[desolateForest]
icon = "icons/Desolateforestsc.jpg"

[desolateForest.name]
en = "Desolate Forest"
zh-Hans = "荒凉森林"

[driedLake]
icon = "icons/Driedlakesc2.png"

[driedLake.name]
en = "Dried Lake"
zh-Hans = "枯涸湖"

[firstStagePool]

[firstStagePool.name]
en = "First Stage Pool"
zh-Hans = "第一关卡池"

[firstThreeStages]

[firstThreeStages.name]
en = "First Three Stages"
zh-Hans = "前三关"

[hiveCluster]
icon = "icons/HiveClusterSC.png"

[hiveCluster.name]
en = "Hive Cluster"
zh-Hans = "虫巢"

[impShrine]

[impShrine.name]
en = "Imp Shrine"
zh-Hans = "小恶魔神龛"

[judgement]

[judgement.name]
en = "Judgement"
zh-Hans = "审判"

[magmaBarracks]
icon = "icons/MagmaBarracksSC.png"

[magmaBarracks.name]
en = "Magma Barracks"
zh-Hans = "熔岩要塞"

[riskOfRain]
icon = "icons/RiskOfRainSC2.png"

[riskOfRain.name]
en = "Risk of Rain"
zh-Hans = "暴雨滂沱"

[skyMeadow]
icon = "icons/SkyMeadowSC.png"

[skyMeadow.name]
en = "Sky Meadow"
zh-Hans = "空中草原"

[sunkenTombs]
icon = "icons/SunkenTombSC.png"

[sunkenTombs.name]
en = "Sunken Tombs"
zh-Hans = "沉没墓园"

[templeOfTheElders]
icon = "icons/EldersSC2.png"

[templeOfTheElders.name]
en = "Temple of the Elders"
zh-Hans = "长老神殿"

[thirdStagePool]

[thirdStagePool.name]
en = "Third Stage Pool"
zh-Hans = "第三关卡池"

[tutorial]

[tutorial.name]
en = "Tutorial"
zh-Hans = "教程"
