schema_version = 1

[acrid]
icon = "icons/AcridPortrait0.png"

[acrid.name]
en = "Acrid"
zh-Hans = "呛鼻毒师"

[arti]
icon = "icons/ArtificerPortrait0.png"

[arti.name]
en = "Artificer"
zh-Hans = "工匠"

[bandit]
icon = "icons/BanditPortrait0.png"

[bandit.name]
en = "Bandit"
zh-Hans = "潜行者"

[chef]
icon = "icons/CHEFPortrait0.png"

[chef.name]
en = "CHEF"
zh-Hans = "大厨"

[commando]
icon = "icons/CommandoPortrait0.png"

[commando.name]
en = "Commando"
zh-Hans = "指挥官"

[drifter]
icon = "icons/DrifterPortrait0.png"

[drifter.name]
en = "Drifter"
zh-Hans = "漂泊者"

[enforcer]
icon = "icons/EnforcerPortrait0.png"

[enforcer.name]
en = "Enforcer"
zh-Hans = "执行者"

[engineer]
icon = "icons/EngineerPortrait0.png"

[engineer.name]
en = "Engineer"
zh-Hans = "工程师"

[hand]
icon = "icons/HAN-DPortrait0.png"

[hand.name]
en = "HAN-D"
zh-Hans = "韩-迪"

[huntress]
icon = "icons/HuntressPortrait0.png"

[huntress.name]
en = "Huntress"
zh-Hans = "女猎人"

[loader]
icon = "icons/LoaderPortrait0.png"

[loader.name]
en = "Loader"
zh-Hans = "装卸工"

[mercenary]
icon = "icons/MercenaryPortrait0.png"

[mercenary.name]
en = "Mercenary"
zh-Hans = "雇佣兵"

[miner]
icon = "icons/MinerPortrait0.png"

[miner.name]
en = "Miner"
zh-Hans = "矿工"

[pilot]
icon = "icons/PilotPortrait0.png"

[pilot.name]
en = "Pilot"
zh-Hans = "领航员"

[sniper]
icon = "icons/SniperPortrait0.png"

[sniper.name]
en = "Sniper"
zh-Hans = "狙击手"
