export const CATEGORIES = new Set([
  "artifact",
  "item",
  "monster_log",
  "other",
  "secret_stage",
  "skill",
  "skin",
  "stage",
  "survivor",
  "trial",
]);

export const ACTIONS_REQUIRING_STAGE = new Set([
  "find",
  "monster_log",
  "secret_stage",
  "world_pickup",
  "world_pickup_button",
  "world_pickup_buttons",
  "world_pickup_enemy_interaction",
  "world_pickup_parkour",
  "world_pickup_puzzle",
  "world_pickup_puzzle_boss",
  "world_pickup_time_limited",
  "world_pickup_timed_buttons",
  "world_prism",
]);

export const ACTIONS = new Set([
  ...ACTIONS_REQUIRING_STAGE,
  "achieve",
  "activate",
  "artifact_loadout_boss_kill",
  "artifact_shards",
  "bank_gold",
  "beat_game",
  "beat_stage",
  "block_damage",
  "clear",
  "collect",
  "complete_objective",
  "complete_trial",
  "cook",
  "deal_damage",
  "detonate",
  "dodge",
  "drown",
  "end_teleporter",
  "eviscerate",
  "fail_shrine",
  "free",
  "get_rank",
  "have_drones",
  "kill",
  "multi_kill",
  "pass_shrine",
  "providence_trials_rank",
  "purchase",
  "reach_level",
  "reach_stat",
  "recycle",
  "reset_cooldown",
  "spread",
  "stay_mode",
  "survive",
  "travel_distance",
  "unlock",
  "use",
  "use_skill",
  "visit_stages",
]);

export const PRECISION = new Set([
  "exact",
  "variant_guide",
  "stage_only",
  "stage_pool",
  "stage_pool_ranked",
  "special_source",
  "hint",
  "missing_route",
  "currently_unobtainable",
  "unknown",
]);

export const CONFIDENCE = new Set(["high", "medium", "low", "unknown"]);

export const STAGE_ROLE = new Set(["current", "route", "target", "source"]);

export const SOURCE_TYPES = new Set(["wiki", "web", "game_metadata", "ai_research"]);

export const STAGES = new Set([
  "desolateForest",
  "driedLake",
  "dampCaverns",
  "skyMeadow",
  "ancientValley",
  "sunkenTombs",
  "magmaBarracks",
  "hiveCluster",
  "templeOfTheElders",
  "riskOfRain",
  "boarBeach",
  "tutorial",
  "judgement",
  "impShrine",
  "firstStagePool",
  "firstThreeStages",
  "thirdStagePool",
]);

export const SURVIVORS = new Set([
  "commando",
  "huntress",
  "enforcer",
  "bandit",
  "hand",
  "engineer",
  "sniper",
  "acrid",
  "mercenary",
  "loader",
  "chef",
  "pilot",
  "arti",
  "drifter",
  "miner",
  "robomando",
]);
